[settings]
file_path = "path-to-datafiles"
spectra_output_path = "path-to-spectra-output-location"
found_peaks_output_path = "path-to-found-peaks-output-location"
lframes = "length-of-frames"
nframes = "number-of-frames-total"
sframes = "number-frames-to-skip"
ref_start = "start-index-of-reference-area"
ref_end = "end-index-of-reference-area"
peak_start = "start-index-of-peak-area"
peak_end = "end-index-of-peak-area"
avg_every = "number-of-frames-to-average"
whole_region_start = "region-start-as-fraction-of-one"
whole_region_end = "region-end-as-fraction-of-one"
peak_criterion = "necessary-height-above-background"